# Docker Compose file to set up the Kafka ecosystem and run producer and consumer services.

services:
  # Zookeeper service - Manages and coordinates the Kafka cluster
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"  # Expose Zookeeper on port 2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000  # Basic Zookeeper configuration

  # Kafka service - The message broker for the pipeline
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"  # Expose Kafka broker on port 9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181  # Connect Kafka to Zookeeper
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092  # Make Kafka accessible on localhost
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1  # Set replication factor to 1 for simplicity
    depends_on:
      - zookeeper  # Ensure Zookeeper starts before Kafka

  # Producer service - Simulates transactions and sends them to Kafka
  producer:
    build:
      context: .  # Use the current directory as the build context
    container_name: producer
    command: python scripts/kafka_producer.py  # Run the producer script
    depends_on:
      - kafka  # Ensure Kafka starts before the producer

  # Consumer service - Consumes transactions from Kafka, processes them, and saves to CSV
  consumer:
    build:
      context: .  # Use the current directory as the build context
    container_name: consumer
    command: python scripts/kafka_consumer.py  # Run the consumer script
    depends_on:
      - kafka  # Ensure Kafka starts before the consumer
